### ISSUE TITLE
Config parsing error log should contain a clue

### ISSUE THREAD

**Issue by azhiltsov** [bookingcom/nanotube#17]
While dealing with #16 I found that it impossible to understand which line is causing the error
./nanotube -config config/config.toml -clusters config/clusters.toml -rules config/rules
2020/02/11 14:39:56 error reading main config: parsing error: toml: cannot load TOML value of type int64 into a Go float

Error should contain a clue what caused the error. 
Name of the parameter and line would be fine

**Comment by grzkv** [comment]
That's a good point. Thanks.

**Comment by grzkv** [comment]
Apparently, this requires changing the lib https://github.com/BurntSushi/toml/issues/217
:man_facepalming:

**Comment by grzkv** [comment]
We cannot fix this without changing the lib. I would rather not change the lib because the one currently in use seems to be working quite well and most used by the community.

So, I suggest we close this issue. @azhiltsov What do you think?

**Comment by grzkv** [comment]
Looking into this further, it turns out that in some cases you still get the location, but not in others. 

I think it makes sense to close this for now.
