### ISSUE TITLE
logging to stdout locks the main thread if you stop consuming it.

### ISSUE THREAD

**Issue by azhiltsov** [bookingcom/nanotube#23]
start nanotube:
```
# cat config/rules.toml
[[rule]]
    regexs = [ ".*" ]
    clusters = [ "local0" ]
```
```
./nanotube -config config/config.toml -clusters config/clusters.toml -rules config/rules.toml  | cat
```
consume its output (1)
```
nc -l 127.0.0.1 8001
```
produce a flow of valid metrics
```
while true ; do echo "bla 1 `date +%s`" | nc -N 127.0.0.1 2003 ; done
```
produce a flow of invalid metrics
```
while true ; do echo "bla bla 1 `date +%s`" | nc -N 127.0.0.1 2003 ; done
```
block the cat
```
kill -19 `pidof cat`
```
observe that (1) stop receiving metrics after a short period.

**Comment by grzkv** [comment]
It is quite weird that `zap.Logger` behaves like this. I would expect it to be non-blocking. This definitely requires further investigation.

For now, this issue will have less impact when #30 is resolved.

**Comment by grzkv** [comment]
I have tried this. This is indeed the case. Looking at the code of `zap`, it is indeed synchronous. This seems a reasonable philosophy for a high-performance logger. We can either leave this be or we can re-implement the [`WriteSyncer`](https://godoc.org/go.uber.org/zap/zapcore#WriteSyncer). @azhiltsov @avereha How critical is this in your opinion?

**Comment by azhiltsov** [comment]
If zap configured to use a file, would it be synchronous as well?

I the real life there could be one foreseeable scenario to observe a blocking behavior -  namely excessive logging. If we can ensure that amount of produced logs is always under control - we should be good.

**Comment by avereha** [comment]
Indeed,  excessive logging can slow down the process.

Another failure mode if we configure it to log to file is that on servers with broken/degraded disks, nanotube will block/stop working.

**Comment by grzkv** [comment]
> If zap configured to use a file, would it be synchronous as well?

Yes.

> I the real life there could be one foreseeable scenario to observe a blocking behaviour - namely excessive logging. If we can ensure that amount of produced logs is always under control - we should be good.

> Indeed, excessive logging can slow down the process.

It is under control. See #25 

> Another failure mode if we configure it to log to file is that on servers with broken/degraded disks, nanotube will block/stop working.

Agreed, let's not do that.

According to feedback, I am closing this. If we hit this in the future, we will tackle it.
