### ISSUE TITLE
Add jitter for reconnection logic

### ISSUE THREAD

**Issue by avereha** [bookingcom/nanotube#32]
We do have exponential backoff but no jitter.

If we have a lot of relays connected to the same host, something goes wrong with the host, all relays loose connection and start to reconnect.
They will retry at exactly the same time, every time, in waves. 
In extreme cases, this can bring back the host down again.

**Comment by dgryski** [comment]
The proper way to do reconnect jitter: https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/
