### ISSUE TITLE
Config ListenTCP and ListenUDP does not understand IPv6

### ISSUE THREAD

**Issue by azhiltsov** [bookingcom/nanotube#65]
it configured as 
ListenTCP="::1:3002"
ListenUDP="::1:3002"

2020/05/06 14:09:28 error launching listener, error parsing ListenTCP option: address ::1:3002: too many colons in address

**Comment by avereha** [comment]
For IPv6 you need to use []. Try `[::1]:3002`.

**Comment by azhiltsov** [comment]
you are right.
