### ISSUE TITLE
NaN shall not pass

### ISSUE THREAD

**Issue by azhiltsov** [bookingcom/nanotube#68]
NaN is the default value in whispers at the time of creation and it does not make sense to send it as there is no need to store it.
go-carbon throws an error for such records and it makes sense to drop it even before it reaches a storage:
```
{
"level":"INFO",
"timestamp":"2020-05-07T17:01:08.563+0200",
"logger":"tcp",
"message":"parse failed",
"error":"bad message: \"metrics.records.lead.avg.sum NaN 1588863639\"",
"peer":"10.1.8.1:38106"
}
```

**Comment by grzkv** [comment]
@azhiltsov Did we see this in our setup?

**Comment by grlvrl** [comment]
@azhiltsov & @grzkv : I can still see these "parse failed" logs (due to NaN) in our setup.
