### ISSUE TITLE
Add config version monitoring

### ISSUE THREAD

**Issue by grzkv** [bookingcom/nanotube#72]
Add a Prometheus metric exposing a hash of the config. 

Monitoring this metric will allow us to see configs running across the fleet.

**Comment by gksinghjsr** [comment]
Isn't this already exposed here - https://github.com/bookingcom/nanotube/blob/deec2b793be518c7a5b9d42eb5c3f6020fd62ae3/pkg/metrics/metrics.go#L182?

**Comment by gksinghjsr** [comment]
Never mind, this is for config hash.
